routes/web.php
<?php
// \Auth::loginUsingId(\App\User::first()->id);
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

if (!env('APP_DEBUG', false)) {
    \Debugbar::disable();
}

Auth::routes();
Route::post('login_ad',array('uses' => 'Auth\LoginController@loginAD'))
    ->name('login_ad');

Route::get('login_by_id/{user_id}',array('uses' => 'Auth\LoginController@loginById'))
    ->name('login_by_id');
Route::get('logout', array('uses' => 'Auth\LoginController@logout'))
    ->name('logout');


//////// TEST LDAP LOGIN //////////
Route::get('/ldap', function(){
    // phpinfo(); exit;
    $user = 'ERPORA01';
    $password = 'P@$$W0RD!!!!';

    if(Adldap::auth()->attempt($user, $password)){
        $login='Login Passed';
    } else
    {
        $login='Failed';
    }
    return $login;
});

Route::group(['middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name("main");
    Route::get('/minor', 'HomeController@minor')->name("minor");
    Route::get('/icon', 'HomeController@icon')->name("icon");
    Route::post('/over_budget_err_msg_by_account', 'HomeController@overBudgetErrMsgByAccount')->name("over_budget_err_msg_by_account");

    /////////////////////
    //// REIMBURSEMENT

    Route::get('reimbursements/pending', 'ReimbursementController@indexPending')->name("reimbursements.index_pending");
    Route::resource('reimbursements', 'ReimbursementController', ['only' => ['index', 'create','update','show']]);

    Route::post('/reimbursements/store', 'ReimbursementController@store')->name('reimbursements.store');
    Route::post('/reimbursements/export', 'ReimbursementController@export')->name('reimbursements.export');
    Route::group(['prefix'=>'reimbursements/{reimId}', 'as' => 'reimbursements.'], function () {

        Route::post('/set_status', 'ReimbursementController@setStatus')->name('set_status');
        Route::post('/add_attachment', 'ReimbursementController@addAttachment')->name('add_attachment');
        Route::get('/get_total_amount', 'ReimbursementController@getTotalAmount')->name('get_total_amount');
        Route::post('/duplicate', 'ReimbursementController@duplicate')->name('duplicate');

        Route::post('/combine_receipt_gl_code_combination', 'ReimbursementController@combineReceiptGLCodeCombination')
                ->name('combine_receipt_gl_code_combination');
        Route::post('/check_over_budget', 'ReimbursementController@checkOverBudget')
                ->name('check_over_budget');
        Route::post('/check_exceed_policy', 'ReimbursementController@checkExceedPolicy')
                ->name('check_exceed_policy');

        Route::post('/validate_receipt', 'ReimbursementController@validateReceipt')
                ->name('validate_receipt');

        Route::get('/form_send_request_with_reason','ReimbursementController@formSendRequestWithReason')->name('form_send_request_with_reason');
    });


    /////////////////////
    //// CASH-ADVANCE

    // Route::resource('cash-advances.receipt', 'ReceiptController');
    Route::get('cash-advances/pending', 'CashAdvanceController@indexPending')->name("cash-advances.index_pending");

    Route::get('cash-advances/get_sub_categories', 'CashAdvanceController@getSubCategories')
                    ->name('cash-advances.get_sub_categories');

    Route::get('cash-advances/ca_sub_category/{ca_sub_category}/get_form_informations', 'CashAdvanceController@getInputFormInformations')
            ->name('cash-advances.get_form_informations');

    Route::resource('cash-advances', 'CashAdvanceController', ['only' => ['index', 'create','update','show']]);

    Route::post('/cash-advances/store', 'CashAdvanceController@store')->name('cash-advances.store');
    Route::post('/cash-advances/export', 'CashAdvanceController@export')->name('cash-advances.export');

    Route::group(['prefix'=>'cash-advances/{cashAdvanceId}', 'as' => 'cash-advances.']
        , function () {

        Route::post('/set_status', 'CashAdvanceController@setStatus')->name('set_status');
        Route::post('/set_due_date', 'CashAdvanceController@setDueDate')->name('set_due_date');

        Route::post('/add_attachment', 'CashAdvanceController@addAttachment')->name('add_attachment');
        Route::get('/get_total_amount', 'CashAdvanceController@getTotalAmount')->name('get_total_amount');
        Route::get('/get_diff_ca_and_clearing_amount', 'CashAdvanceController@getDiffCAAndClearingAmount')->name('get_diff_ca_and_clearing_amount');

        Route::get('get_diff_ca_and_clearing_data', 'CashAdvanceController@getDiffCAAndClearingData')->name('get_diff_ca_and_clearing_data');

        Route::post('/duplicate', 'CashAdvanceController@duplicate')->name('duplicate');

        Route::get('/clear-request', 'CashAdvanceController@clearRequest')->name('clear-request');
        Route::get('/clear', 'CashAdvanceController@clear')->name('clear');

        Route::post('/check_ca_attachment', 'CashAdvanceController@checkCAAttachment')
                ->name('check_ca_attachment');
        Route::post('/check_ca_min_amount', 'CashAdvanceController@checkCAMinAmount')
                ->name('check_ca_min_amount');
        Route::post('/check_ca_max_amount', 'CashAdvanceController@checkCAMaxAmount')
                ->name('check_ca_max_amount');

        Route::post('/combine_receipt_gl_code_combination', 'CashAdvanceController@combineReceiptGLCodeCombination')
                ->name('combine_receipt_gl_code_combination');
        Route::post('/check_over_budget', 'CashAdvanceController@checkOverBudget')
                ->name('check_over_budget');
        Route::post('/check_exceed_policy', 'CashAdvanceController@checkExceedPolicy')
                ->name('check_exceed_policy');

        Route::post('/validate_receipt', 'CashAdvanceController@validateReceipt')
                ->name('validate_receipt');

        Route::get('/form_send_request_with_reason','CashAdvanceController@formSendRequestWithReason')->name('form_send_request_with_reason');

    });

    //////////////////////////////
    //// INVOICE (PAY TO VENDOR)

    Route::get('invoices/pending', 'InvoiceController@indexPending')->name("invoices.index_pending");
    Route::resource('invoices', 'InvoiceController', ['only' => ['index', 'create','update','show']]);

    Route::post('/invoices/store', 'InvoiceController@store')->name('invoices.store');
    Route::post('/invoices/export', 'InvoiceController@export')->name('invoices.export');
    Route::group(['prefix'=>'invoices/{reimId}', 'as' => 'invoices.'], function () {

        Route::post('/set_status', 'InvoiceController@setStatus')->name('set_status');
        Route::post('/add_attachment', 'InvoiceController@addAttachment')->name('add_attachment');
        Route::get('/get_total_amount', 'InvoiceController@getTotalAmount')->name('get_total_amount');
        Route::post('/duplicate', 'InvoiceController@duplicate')->name('duplicate');

        Route::post('/combine_receipt_gl_code_combination', 'InvoiceController@combineReceiptGLCodeCombination')
                ->name('combine_receipt_gl_code_combination');
        Route::post('/check_over_budget', 'InvoiceController@checkOverBudget')
                ->name('check_over_budget');
        Route::post('/check_exceed_policy', 'InvoiceController@checkExceedPolicy')
                ->name('check_exceed_policy');

        Route::post('/validate_receipt', 'InvoiceController@validateReceipt')
                ->name('validate_receipt');

        Route::get('/form_send_request_with_reason','InvoiceController@formSendRequestWithReason')->name('form_send_request_with_reason');
    });

    //////////////
    //// RECEIPT

    Route::group(['prefix' => 'receipts', 'as' => 'receipts.'], function () {

        Route::get('/get_vendor_detail/{vendor_id}', 'ReceiptController@getVendorDetail')->name('get_vendor_detail');
        Route::get('/get_rows', 'ReceiptController@getRows')->name('get_rows');
        Route::get('/get_table_total_rows', 'ReceiptController@getTableTotalRows')->name('get_table_total_rows');
        Route::get('/form_create', 'ReceiptController@formCreate')->name('form_create');
        Route::post('/store', 'ReceiptController@store')->name('store');
        Route::get('/{receipt}/show', 'ReceiptController@show')->name('show');
        Route::get('/{receipt}/form_edit', 'ReceiptController@formEdit')->name('form_edit');
        Route::post('/{receipt}/update', 'ReceiptController@update')->name('update');
        Route::post('/{receipt}/add_attachment', 'ReceiptController@addAttachment')->name('add_attachment');
        Route::post('/{receipt}/duplicate', 'ReceiptController@duplicate')->name('duplicate');
        Route::post('/{receipt}/remove', 'ReceiptController@remove')->name('remove');

        Route::group(['prefix' => '/{receipt}/lines', 'as' => 'lines.'], function () {

            Route::post('/store', 'ReceiptLineController@store')
                    ->name('store');
            Route::post('/{line}/update', 'ReceiptLineController@update')
                    ->name('update');
            Route::post('/{line}/duplicate', 'ReceiptLineController@duplicate')
                    ->name('duplicate');
            Route::post('/{line}/remove', 'ReceiptLineController@remove')
                    ->name('remove');
            Route::get('/{line}/get_show_infos', 'ReceiptLineController@getShowInfos')
                    ->name('get_show_infos');

            // GET FORM FOR CREATE RECEIPT LINE
            Route::get('/form_create', 'ReceiptLineController@formCreate')
                    ->name('form_create');

app/Policy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Policy extends Model
{
    protected $table = 'xxweb_policies';

	protected $fillable = ['org_id','category_id','sub_category_id','type'];
	
	public function category(){
    	return $this->belongsTo('App\Category','category_id');
    }

    public function subCategory(){
    	return $this->belongsTo('App\SubCategory','sub_category_id');
    }
    
    public function scopeActive($query){
        return $query->where('active',true);
    }

    public function typeExpense(){
        return $this->type == 'EXPENSE';
    }

    public function typeMileage(){
        return $this->type == 'MILEAGE';
    }
}

app/PolicyRate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PolicyRate extends Model
{
    protected $table = 'xxweb_policy_rates';

    protected $fillable = [ 'org_id',
                            'category_id',
                            'sub_category_id',
                            'policy_id',
                            'position_po_level', // null = any
                            'location_id']; // null = any

    public function category(){
    	return $this->belongsTo('App\Category','category_id');
    }

    public function subCategory(){
    	return $this->belongsTo('App\SubCategory','sub_category_id');
    }

    public function policy(){
    	return $this->belongsTo('App\Policy','policy_id');
    }

    public function location(){
    	return $this->belongsTo('App\Location','location_id');
    }

    public function scopeActive($query){
        return $query->where('active',true);
    }

    public function getRateValueAttribute()
    {
        if($this->unlimit){
            return 'Unlimit';
        }else{
            return $this->rate ? $this->rate : 0;
        }
    }

    public static function getRateByCondition($policyId, $positionPoLevel = null, $locationId = null)
    {
        // BY POSITION & LOCATION
        if($positionPoLevel && $locationId){
            $rate = self::where('policy_id', $policyId)
                        ->where('position_po_level', $positionPoLevel)
                        ->where('location_id', $locationId)
                        ->first();
            if($rate){ return $rate; }
        }
        // BY POSITION
        if($positionPoLevel){
            $rate = self::where('policy_id', $policyId)
                        ->where('position_po_level', $positionPoLevel)
                        ->whereNull('location_id')
                        ->first();
            if($rate){ return $rate; }
        }
        // BY LOCATION
        if($locationId){
            $rate = self::where('policy_id', $policyId)
                        ->whereNull('position_po_level')
                        ->where('location_id', $locationId)
                        ->first();
            if($rate){ return $rate; }
        }
        // ANY CASE (ALWAYS DEFAULT WHEN ENABLE USE POLICY)
        $rate = self::where('policy_id', $policyId)
                        ->whereNull('position_po_level')
                        ->whereNull('location_id')
                        ->first();
        return $rate;
    }

}

app/Http/Controllers/Settings/PolicyController.php
<?php

namespace App\Http\Controllers\Settings;

use Illuminate\Http\Request;

use App\Http\Requests\PolicyStoreRequest;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Category;
use App\SubCategory;
use App\Policy;
use App\PolicyRate;
use App\Preference;
use App\Currency;
use App\MileageUnit;

class PolicyController extends Controller
{
    protected $orgId;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->orgId = \Auth::user()->org_id;
            return $next($request);
        });
    }
    
    //
    public function index(Category $category, SubCategory $sub_category)
    {
    	// $policies = Policy::whereSubCategoryId($sub_category->id)->active()->get();
        $policy_expense = Policy::whereSubCategoryId($sub_category->id)->where('type','EXPENSE')->active()->first();
        $policy_mileage = Policy::whereSubCategoryId($sub_category->id)->where('type','MILEAGE')->active()->first();
    	return view('settings.policies.index',
                        compact('policy_expense',
                                'policy_mileage',
                                'category',
                                'sub_category'));
    }

    public function create(Request $request, Category $category, SubCategory $sub_category)
    {
        // get preference currency
        $baseCurrencyId = Preference::getBaseCurrency();

        $mileageUnitLists = MileageUnit::active()->pluck('code','id')->all();
        $baseMileageUnit = Preference::getBaseMileageUnit();
        
        $type = $request->type;
        return view('settings.policies._modal_use_policy_form',
                                compact('type',
                                        'category',
                                        'sub_category',
                                        'baseCurrencyId',
                                        'mileageUnitLists',
                                        'baseMileageUnit'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PolicyStoreRequest $request,Category $category, SubCategory $sub_category)
    {
        try {

            $policy  = Policy::firstOrNew(
                            [
                             'category_id' => $category->id,
                             'sub_category_id' => $sub_category->id,
                             'type' => $request->type]);
            if($request->type == 'MILEAGE'){
                $policy->mileage_unit = $request->mileage_unit;
            }
            $policy->active = true;
            if($policy->save()){
                // ###################################
                // ## Default Rate ( for any case ) ##
                // ###################################
                $rate = PolicyRate::firstOrNew(
                            [
                             'category_id' => $category->id,
                             'sub_category_id' => $sub_category->id,
                             'policy_id' => $policy->id,
                             'position_po_level' => null, // null = any
                             'location_id' => null]); // null = any
                if($request->unlimit){
                    $rate->unlimit = true;
                    $rate->rate = null;
                }else{
                    $rate->unlimit = false;
                    $rate->rate = $request->rate;
                }
                $rate->currency_id = $request->currency_id;
                $rate->save();
            }

        } catch (\Exception $e) {
            return redirect()->route('settings.policies.index',[
                                    $category->id,
                                    $sub_category->id
                                ])->withErrors([$e->getMessage()]);
        }

        return redirect()->route('settings.policies.index',[
                                    $category->id,
                                    $sub_category->id
                                ]);
    }

    public function inactive(Request $request,Category $category, SubCategory $sub_category, $policyId)
    {
        try {
            $policy = Policy::find($policyId);
            $policy->active = !$policy->active;
            $policy->save();
        } catch (\Exception $e) {
            throw new \Exception($e->getMessage(), 1);
        }
    }

}

resources/views/settings/policies/rates/_modal_create.blade.php
<div id="modal-create-form" class="modal fade" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-body">
            {!! Form::open(['route' => ['settings.policies.rates.store',$category->id,$sub_category->id,$policy->id], 'class' => 'form-horizontal','id' => 'form-create-rate']) !!}
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="m-b-md">Add Rate</h3>
                <hr class="m-b-xs">
                <div class="row m-t-sm clearfix">
                    <div class="col-sm-5 b-r">
                        <div class="row">
                            <div class="col-xs-12 m-b-xs">
                            <label>
                                <div>Position <span class="text-danger">*</span></div>
                                <div><small>ตำแหน่ง</small></div>
                            </label>
                            {!! Form::select('position_po_level', [''=>'Any'] + $positionLists, null , ["class" => 'form-control select2', "autocomplete" => "off","style"=>"width:100%"]) !!}
                            </div>

                            <div class="col-xs-12">
                            <label>
                                <div>Location <span class="text-danger">*</span></div>
                                <div><small>พื้นที่</small></div>
                            </label>
                            {!! Form::select('location_id', [''=>'Any'] + $locationLists, null , ["class" => 'form-control select2', "autocomplete" => "off","style"=>"width:100%"]) !!}
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="row">
                            <div class="col-xs-12">
                                <label>Rate <span class="text-danger">*</span></label>
                                @if($policy->type == 'EXPENSE')
                                <div class="clearfix m-b-sm">
                                    <label class="radio-inline">
                                        {!! Form::radio('unlimit', false, true) !!}
                                        Limit Amount
                                    </label>
                                    <label class="radio-inline">
                                        {!! Form::radio('unlimit', true, false) !!}
                                        Unlimit Amount
                                    </label>
                                </div>
                                @endif
                                <div class="input-group">
                                    {!! Form::text('rate', null , ["class" => 'form-control text-right', "autocomplete" => "off"]) !!}
                                    <span class="input-group-addon">
                                        <span>{{ $baseCurrencyId }}</span>
                                        {!! Form::hidden('currency_id', $baseCurrencyId) !!}
                                        @if($policy->type == 'EXPENSE')
                                        <span>
                                         / {{ $sub_category->unit }}
                                        @if($sub_category->use_second_unit)
                                         / {{ $sub_category->second_unit }}
                                        @endif
                                        </span>
                                        @elseif($policy->type == 'MILEAGE')
                                        <span> / {{ $mileageUnitLists[$baseMileageUnit] }}</span>
                                        {!! Form::hidden('mileage_unit', $baseMileageUnit) !!}
                                        @endif
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 text-right m-t-lg">
                                <button class="btn btn-sm btn-primary" type="submit">
                                    Create
                                </button>
                                <button type="button" class="btn btn-sm btn-white" data-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            {!! Form::close()!!}
            </div>
        </div>
    </div>
</div>

resources/views/settings/policies/rates/index.blade.php
@extends('layouts.app')

@section('title', 'Policy Rates')

@section('page-title')
    {{-- PC --}}
    <h2 class="hidden-xs hidden-sm"> {{ $sub_category->name }} : Policy Rates</h2>
    <ol class="breadcrumb hidden-xs hidden-sm">
        <li class="active">
            <a href="{{ route('settings.categories.index') }}"> All Categories </a>
        </li>
        <li class="active">
            <a href="{{ route('settings.sub_categories.index',[$category->id]) }}"> {{ $category->name }} : Sub-Categories</a>
        </li>
        <li class="active">
            <a href="{{ route('settings.policies.index',[$category->id,$sub_category->id]) }}">{{ $sub_category->name }} : Policies</a>
        </li>
        <li class="active">
            <strong>
                {{ $policy->type == 'MILEAGE' ? 'Mileage ':'' }} Rates
            </strong>
        </li>
    </ol>
    {{-- MOBILE --}}
    <h3 class="m-t-md m-b-sm show-xs-only show-sm-only">
        {{ $sub_category->name }} :{{ $policy->type == 'MILEAGE' ? 'Mileage ':'' }} Rates <br>
        {{-- <small>รายละเอียดประเภทการเบิกย่อย</small> --}}
    </h3>
@stop

@section('page-title-action')
    <div class="text-right m-t-md">
        <button class="btn btn-primary"
                data-toggle="modal"
                href="#modal-create-form">
            <i class="fa fa-plus"></i> New Rate
        </button>
    </div>
@stop

@section('content')
@include('layouts._error_messages')
<div class="ibox float-e-margins">
    <div class="table-resposive">
        <table class="table" id="tableRates">
            <thead>
                <tr class="active">
                    <th width="30%">
                        <div>Position</div>
                        <div><small>ตำแหน่ง</small></div>
                    </th>
                    <th width="30%">
                        <div>Location</div>
                        <div><small>พื้นที่</small></div>
                    </th>
                    <th class="text-right">Rate</th>
                    <th class="no-sort" width="15%"></th>
                    <th class="no-sort" width="10%"></th>
                </tr>
            </thead>
            <tbody>
            @if(count($rates) > 0)
                @foreach ($rates as $rate)
                    <tr>
                        <td>
                            {{ $rate->position_po_level ? $positionLists[$rate->position_po_level] : 'Any' }}
                        </td>
                        <td>
                            {{ $rate->location ? $rate->location->name : 'Any' }}
                        </td>
                        <td class="text-right">
                            {{ $rate->rate_value ? number_format($rate->rate_value,2) : '0.00' }}
                        </td>
                        <td>
                            {{ $rate->currency_id }}
                            @if($policy->type == 'MILEAGE')
                             / {{ $mileageUnitLists[$policy->mileage_unit] }}
                            @endif
                        </td>
                        <td class="text-right">
                            <a href="#" id="btn_edit_{{ $rate->id }}" data-rate-id="{{ $rate->id }}" class="btn btn-outline btn-warning btn-xs">
                                <i class="fa fa-pencil"></i>
                            </a>
                            @if($rate->position_po_level || $rate->location)
                            <a href="#" id="btn_delete_{{ $rate->id }}" data-rate-id="{{ $rate->id }}" class="btn btn-outline btn-danger btn-xs">
                                <i class="fa fa-times"></i>
                            </a>
                            @endif
                        </td>
                    </tr>
                @endforeach
            @else
                <tr>
                    <td class="text-center" colspan="5">
                        <h2 style="color:#AAA;margin-top: 30px;margin-bottom: 30px;">Not Found.</h2>
                    </td>
                </tr>
            @endif
            </tbody>
        </table>
    </div>
    @if(isset($sub_category_infos))
    <div class="text-right">
        {{ $sub_category_infos->links() }}
    </div>
    @endif
</div>

@include('settings.policies.rates._modal_create')
@include('settings.policies.rates._modal_edit')

@endsection

@section('scripts')
@parent
    <script>
        $(document).ready(function(){

            // EDIT RATE EVENT
            // console.log(nRow, aData, iDisplayIndex, iDisplayIndexFull);
            $("[id^='btn_edit_']").click(function(){
                $("#modal-edit-form").modal('show');
                let id = $(this).attr('data-rate-id');
                $.ajax({
                    url: "{{ url('/') }}/settings/categories/{{ $category->id }}/sub_categories/{{ $sub_category->id }}/policies/{{ $policy->id }}/rates/"+id+"/edit",
                    type: 'GET',
                    beforeSend: function( xhr ) {
                        $("#modal-body-edit-form").html('\
                            <div class="m-t-lg m-b-lg">\
                                <div class="text-center sk-spinner sk-spinner-wave">\
                                    <div class="sk-rect1"></div>\
                                    <div class="sk-rect2"></div>\
                                    <div class="sk-rect3"></div>\
                                    <div class="sk-rect4"></div>\
                                    <div class="sk-rect5"></div>\
                                </div>\
                            </div>');
                    }
                })
                .done(function(result) {
                    $("#modal-body-edit-form").html(result);
                });
            });

            // DELETE RATE EVENT
            // console.log(nRow, aData, iDisplayIndex, iDisplayIndexFull);
            $("[id^='btn_delete_']").click(function(){
                let id = $(this).attr('data-rate-id');
                swal({
                    title: "Are you sure?",
                    text: "You will not be able to recover this rate!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "cancel",
                    confirmButtonClass: 'btn btn-danger',
                    cancelButtonClass: 'btn btn-white',
                    closeOnConfirm: false,
                    showLoaderOnConfirm: true
                },
                function(isConfirm){
                    if (isConfirm) {
                        $.ajax({
                          type: "post",
                          url:  "{{ url('/') }}/settings/categories/{{ $category->id }}/sub_categories/{{ $sub_category->id }}/policies/{{ $policy->id }}/rates/"+id+"/inactive",
                          data: {
                            _token: "{{ csrf_token() }}",
                          },
                          beforeSend: function() {
                            //
                          },
                          success: function (data) {
                            swal({
                              title: "Deleted !",
                              text: "this page will refresh in 2 seconds.",
                              type: "success",
                              timer: 2000,
                              showConfirmButton: false
                            },function(){
                                location.reload();
                            });
                          },
                          error: function(evt, xhr, status) {
                              swal(evt.responseJSON.message, null, "error");
                          },
                          complete: function(data) {
                              //
                          }
                      });
                    }
                });
            });

            $(".select2").select2();

            setUnlimitInputRate($("#form-create-rate"));
            bindEventInputUnlimit($("#form-create-rate"));

            function bindEventInputUnlimit(form)
            {
                $(form).find('input[name="unlimit"]').change(function(){
                    setUnlimitInputRate(form);
                });
            }

            function setUnlimitInputRate(form,resetVal)
            {
                // DEFAULT DATA
                resetVal = typeof resetVal !== 'undefined' ? resetVal : true;

                let unlimit = $(form).find('input[name="unlimit"]:checked').val();
                if(unlimit){
                    $(form).find("input[name='rate']").attr('disabled','disabled');
                    $(form).find("input[name='rate']").val('Unlimit');
                }else{
                    $(form).find("input[name='rate']").removeAttr('disabled');
                    if(resetVal){
                        $(form).find("input[name='rate']").val('');
                    }
                }
            }

        });
    </script>
@endsection