routes/web.php
        Route::post('/duplicate', 'InvoiceController@duplicate')->name('duplicate');

        Route::post('/combine_receipt_gl_code_combination', 'InvoiceController@combineReceiptGLCodeCombination')
                ->name('combine_receipt_gl_code_combination');
        Route::post('/check_over_budget', 'InvoiceController@checkOverBudget')
                ->name('check_over_budget');
        Route::post('/check_exceed_policy', 'InvoiceController@checkExceedPolicy')
                ->name('check_exceed_policy');

        Route::post('/validate_receipt', 'InvoiceController@validateReceipt')
                ->name('validate_receipt');

        Route::get('/form_send_request_with_reason','InvoiceController@formSendRequestWithReason')->name('form_send_request_with_reason');
    });

    //////////////
    //// RECEIPT

    Route::group(['prefix' => 'receipts', 'as' => 'receipts.'], function () {

        Route::get('/get_vendor_detail/{vendor_id}', 'ReceiptController@getVendorDetail')->name('get_vendor_detail');
        Route::get('/get_rows', 'ReceiptController@getRows')->name('get_rows');
        Route::get('/get_table_total_rows', 'ReceiptController@getTableTotalRows')->name('get_table_total_rows');
        Route::get('/form_create', 'ReceiptController@formCreate')->name('form_create');
        Route::post('/store', 'ReceiptController@store')->name('store');
        Route::get('/{receipt}/show', 'ReceiptController@show')->name('show');
        Route::get('/{receipt}/form_edit', 'ReceiptController@formEdit')->name('form_edit');
        Route::post('/{receipt}/update', 'ReceiptController@update')->name('update');
        Route::post('/{receipt}/add_attachment', 'ReceiptController@addAttachment')->name('add_attachment');
        Route::post('/{receipt}/duplicate', 'ReceiptController@duplicate')->name('duplicate');
        Route::post('/{receipt}/remove', 'ReceiptController@remove')->name('remove');

        Route::group(['prefix' => '/{receipt}/lines', 'as' => 'lines.'], function () {

            Route::post('/store', 'ReceiptLineController@store')
                    ->name('store');
            Route::post('/{line}/update', 'ReceiptLineController@update')
                    ->name('update');
            Route::post('/{line}/duplicate', 'ReceiptLineController@duplicate')
                    ->name('duplicate');
            Route::post('/{line}/remove', 'ReceiptLineController@remove')
                    ->name('remove');
            Route::get('/{line}/get_show_infos', 'ReceiptLineController@getShowInfos')
                    ->name('get_show_infos');

            // GET FORM FOR CREATE RECEIPT LINE
            Route::get('/form_create', 'ReceiptLineController@formCreate')
                    ->name('form_create');
            Route::get('/get_sub_categories', 'ReceiptLineController@getSubCategories')
                    ->name('get_sub_categories');
            Route::get('/sub_category/{sub_category}/get_form_informations', 'ReceiptLineController@getInputFormInformations')
                    ->name('sub_category.get_form_informations');
            Route::get('/sub_category/{sub_category}/get_form_amount', 'ReceiptLineController@getInputFormAmount')
                    ->name('sub_category.get_form_amount');

            // GET FORM FOR EDIT RECEIPT LINE
            Route::get('/{line}/form_edit', 'ReceiptLineController@formEdit')
                    ->name('form_edit');
            Route::get('/{line}/get_form_edit_informations', 'ReceiptLineController@getInputFormEditInformations')
                    ->name('get_form_edit_informations');
            Route::get('/{line}/get_form_edit_amount', 'ReceiptLineController@getInputFormEditAmount')
                    ->name('get_form_edit_amount');

        });

    });


    //////////////
    //// SETTING

    Route::group(['prefix' => 'settings', 'namespace' => 'Settings', 'as' => 'settings.','middleware'=>['superuser']],
        	function () {

        // CA Categories
        Route::resource('ca_categories', 'CACategoriesController',
            ['only' => ['index', 'create', 'store', 'edit', 'update']]
        );
        Route::post('ca_categories/{ca_category}/remove', 'CACategoriesController@remove')->name("ca_categories.remove");

        Route::group(['prefix'=>'ca_categories/{ca_category}'], function () {

            // CA Sub-Categories
            Route::get('ca_sub_categories/input_sub_account_code/', 'CASubCategoryController@inputSubAccountCode')->name("input_sub_account_code");
            Route::resource('ca_sub_categories', 'CASubCategoryController');
            Route::group(['prefix'=>'ca_sub_categories/{ca_sub_category}'], function () {

                // CA Sub-Categories Info.
                Route::group(['as'=>'ca_sub_categories.'], function () {
                    Route::resource('infos', 'CASubCategoryInfoController');
                    Route::get('/input_form_type/{input_form_type}', 'CASubCategoryInfoController@inputFormType')
                                ->name("input_form_type");
                    Route::group(['prefix'=>'infos/{info}', 'as'=>'infos.'], function () {
                        // Sub-Categories Info. Inactive
                        Route::post('/inactive', 'CASubCategoryInfoController@inactive')
                                    ->name("inactive");
                    });
                });

            });
        });

        // REIM Categories
        Route::resource('categories', 'CategoriesController',
            ['only' => ['index', 'create', 'store', 'edit', 'update']]
        );
        Route::post('categories/{category}/remove', 'CategoriesController@remove')
                                    ->name("categories.remove");

        Route::group(['prefix'=>'categories/{category}'], function () {

            // Sub-Categories
            Route::get('sub_categories/input_sub_account_code/', 'SubCategoryController@inputSubAccountCode')->name("input_sub_account_code");
            Route::resource('sub_categories', 'SubCategoryController');
            Route::group(['prefix'=>'sub_categories/{sub_category}'], function () {

                // Sub-Categories Info.
                Route::group(['as'=>'sub_categories.'], function () {
                    Route::resource('infos', 'SubCategoryInfoController');
                    Route::get('/input_form_type/{input_form_type}', 'SubCategoryInfoController@inputFormType')
                                ->name("input_form_type");
                    Route::group(['prefix'=>'infos/{info}', 'as'=>'infos.'], function () {
                        // Sub-Categories Info. Inactive
                        Route::post('/inactive', 'SubCategoryInfoController@inactive')
                                    ->name("inactive");
                    });
                });

                // Policy
                Route::resource('policies', 'PolicyController',
                    ['only' => ['index', 'create', 'store']]);
                Route::group(['prefix'=>'policies/{policy}', 'as'=>'policies.'], function () {
                    // Policy Inactive
                    Route::post('/inactive', 'PolicyController@inactive')
                                ->name("inactive");

                    Route::resource('rates', 'PolicyRateController');
                    Route::group(['prefix'=>'rates/{rate}', 'as'=>'rates.'], function () {
                        // Policy Rate Inactive
                        Route::post('/inactive', 'PolicyRateController@inactive')
                                    ->name("inactive");
                    });

            	});

            });
        });

        // Locations
        Route::resource('locations', 'LocationController',['only'=>['index', 'create', 'store', 'edit', 'update']]);
        Route::post('locations/inactive', 'LocationController@inactive')
                                    ->name("locations.inactive");

        // User
        Route::resource('users', 'UserController',['only'=>['index', 'edit', 'update']]);
        Route::post('users/inactive', 'UserController@inactive')
                                    ->name("users.inactive");
        Route::post('users/sync_all_users', 'UserController@syncAllUsers')
                                    ->name("users.sync_all_users");

        Route::get('preferences', 'PreferenceController@index')->name('preferences.index');
        Route::post('preferences/update', 'PreferenceController@update')->name('preferences.update');
        Route::post('preferences/slice_json', 'PreferenceController@sliceJson')->name('preferences.slice_json');

    });

    //////////////////
    //// ATTACHMENTS

    Route::get('attachments/{attachment_id}/download', ['as' => 'attachments.download', 'uses' => 'AttachmentsController@download']);
    Route::get('attachments/{attachment_id}/image', ['as' => 'attachments.image', 'uses' => 'AttachmentsController@image']);
    Route::post('attachments/{attachment_id}/image_modal', ['as' => 'attachments.image_modal', 'uses' => 'AttachmentsController@imageModal']);
    Route::post('/attachments/{attachment_id}/remove', ['as' => 'attachments.remove', 'uses' => 'AttachmentsController@remove']);
    Route::delete('/attachments/{attachment_id}/remove', ['as' => 'attachments.remove', 'uses' => 'AttachmentsController@remove']);

    /////////////////////
    // AP INTERFACE LOG
    Route::group(['middleware'=>['superuser']], function () {

        Route::get('interface_ap', [
                    'as' => 'interface_ap.index',
                    'uses' => 'InterfaceAPController@index'
                ]);
        Route::get('interface_ap/{interface_ap_header_id}/show', [
                    'as' => 'interface_ap.show',
                    'uses' => 'InterfaceAPController@show'
                ]);
        Route::post('interface_ap/{interface_ap_header_id}/re_process', [
                    'as' => 'interface_ap.re_process',

app/CACategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CACategory extends Model
{
    protected $table = 'xxweb_ca_categories';
	
    public function scopeActive($query){
        return $query->where('active',true);
    }
}

app/Http/Controllers/Settings/CACategoriesController.php
<?php

namespace App\Http\Controllers\Settings;

use Illuminate\Http\Request;

use App\Http\Requests\CACategoriesStoreRequest;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\CACategory;
use App\Icon;

class CACategoriesController extends Controller
{
    protected $orgId;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->orgId = \Auth::user()->org_id;
            return $next($request);
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ca_categories = CACategory::active()->get();
        return view('settings.ca_categories.index', compact('ca_categories'));
    }

    public function create()
    {
        $iconLists = Icon::data()->sortBy('name')->pluck('name','code')->all();

        return view('settings.ca_categories.create', 
            compact('iconLists'));
    }

    public function store(CACategoriesStoreRequest $request)
    {
        $ca_category = new CACategory();
        $ca_category->icon = $request->icon ? $request->icon : null;
        $ca_category->name = $request->name;
        // $ca_category->org_id = $this->orgId;
        $ca_category->description = $request->description;
        $ca_category->save();

        return redirect()->route('settings.ca_categories.index');
    } 


    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(CACategory $ca_category)
    {
        $iconLists = Icon::data()->sortBy('name')->pluck('name','code')->all();

        return view('settings.ca_categories.edit', 
            compact('ca_category','iconLists'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(CACategoriesStoreRequest $request, CACategory $ca_category)
    {
    	$ca_category->name = $request->name;
        $ca_category->icon = $request->icon ? $request->icon : null;
        $ca_category->description = $request->description;
        $ca_category->save();

        return redirect()->route('settings.ca_categories.index');
    }

    public function remove(Request $request, CACategory $ca_category)
    {
        \DB::beginTransaction();
        try {
            // REMOVE CATEGORY
            $ca_category->active = false;
            $ca_category->save();

        } catch (\Exception $e) {
            \DB::rollBack();
            \Log::error($e->getMessage());
        }
        \DB::commit();

        if($request->ajax()){
            return \Response::json("success", 200);
        }else{
            return redirect()->route('settings.ca_categories.index');
        }
    }
}

app/Http/Controllers/Settings/CategoriesController.php
<?php

namespace App\Http\Controllers\Settings;

use Illuminate\Http\Request;

use App\Http\Requests\CategoriesStoreRequest;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Category;
use App\Icon;

class CategoriesController extends Controller
{
    protected $orgId;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->orgId = \Auth::user()->org_id;
            return $next($request);
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::active()->get();
        return view('settings.categories.index', compact('categories'));
    }

    public function create()
    {
        $iconLists = Icon::data()->sortBy('name')->pluck('name','code')->all();
        return view('settings.categories.create', 
            compact('iconLists'));
    }

    public function store(CategoriesStoreRequest $request)
    {
        $category = new Category();
        // $category->org_id = $this->orgId;
        $category->name = $request->name;
        $category->icon = $request->icon ? $request->icon : null;
        $category->description = $request->description;
        $category->save();

        return redirect()->route('settings.categories.index');
    } 


    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $iconLists = Icon::data()->sortBy('name')->pluck('name','code')->all();
        return view('settings.categories.edit', 
            compact('category','iconLists'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(CategoriesStoreRequest $request, Category $category)
    {
        $category->name = $request->name;
        $category->icon = $request->icon ? $request->icon : null;
        $category->description = $request->description;
        $category->save();

        return redirect()->route('settings.categories.index');
    }

    public function remove(Request $request, Category $category)
    {
        \DB::beginTransaction();
        try {
            // INACTIVE SUBCATEGORY OF THIS CATEGORY
            if(count($category->subCategories) > 0){
                foreach($category->subCategories as $subCategory){
                    $subCategory->active = false;
                    $subCategory->save();
                }
            }
            // REMOVE CATEGORY
            $category->active = false;
            $category->save();

        } catch (\Exception $e) {
            \DB::rollBack();
            \Log::error($e->getMessage());
        }
        \DB::commit();

        if($request->ajax()){
            return \Response::json("success", 200);
        }else{
            return redirect()->route('settings.categories.index');
        }
    }

}

resources/views/settings/ca_categories/_ddl_sub_account_code.blade.php
{!! Form::select('sub_account_code', $subAccountLists , $subAccountCode, ["class" => 'form-control select2', "autocomplete" => "off"]) !!}
<script type="text/javascript">
	$(document).ready(function(){
		$("select[name='sub_account_code']").select2();
	});
</script>

resources/views/settings/ca_categories/_form.blade.php
<div class="form-group">
    <label for="name" class="col-md-2 control-label label-no-padding">
        <div>Name <span class="text-danger">*</span></div>
        <div class="m-r-sm"><small>ชื่อ</small></div>
    </label> 
    <div class="col-md-4">
        {!! Form::text('name', null , ["class" => 'form-control', "autocomplete" => "off"]) !!}
    </div>
    <label for="icon" class="col-md-1 control-label label-no-padding">
        <div>Icon <span class="text-danger">*</span></div>
        <div class="m-r-sm"><small>ไอคอน</small></div> 
    </label> 
    <div class="col-md-2">
        {!! Form::select('icon',[''=>'']+$iconLists , null , ["class" => 'form-control icon-picker', "autocomplete" => "off",'id'=>'ddl_icon']) !!}
    </div>
    <div class="col-md-1">
        <div class="show-xs-only show-sm-only m-t-sm">&nbsp;</div>
        <div id="div_icon" class="text-center text-navy" style="font-size:2em;">
        @if(isset($ca_category))
            @include('layouts._icon',['iconClass'=>$ca_category->icon])
        @endif
        </div>
    </div>
</div>
<div class="form-group">
    <label for="name" class="col-md-2 control-label label-no-padding">
        <div>Description <span class="text-danger">*</span></div>
        <div class="m-r-sm"><small>รายละเอียด</small></div> 
    </label>
    <div class="col-md-8">
        {!! Form::text('description', null , ["class" => 'form-control', "autocomplete" => "off"]) !!}
    </div>
</div>
<hr>
<div class="form-group">
    <div class="col-md-offset-2 col-md-6">
        <button type="submit" class="btn btn-primary" data-disable-with="Processing...">Save</button>
        <a href="{{ route('settings.ca_categories.index') }}" class="btn btn-white">Cancel</a>
    </div>
</div>

@section('scripts')
@parent
    <script>
        $(document).ready(function() {

            $("select[name='icon']").change(function(){
                var icon = $("select[name='icon'] option:selected").val();
                $.ajax({
                    url: "{{ url('/') }}/icon",
                    data: { icon : icon },
                    type: 'GET',
                    beforeSend: function( xhr ) {
                        $("#div_icon").html('<div class="sk-spinner sk-spinner-wave" style="height:20px">\
                                    <div class="sk-rect1"></div>\
                                    <div class="sk-rect2"></div>\
                                    <div class="sk-rect3"></div>\
                                    <div class="sk-rect4"></div>\
                                    <div class="sk-rect5"></div>\
                                </div>');
                    }
                })
                .done(function(result) {
                    $("#div_icon").html(result);
                });
            });

        });
    </script>
@endsection

resources/views/settings/ca_categories/create.blade.php
@extends('layouts.app')

@section('title', 'Cash Advance Categories')

@section('page-title')
    {{-- PC --}}
    <h2 class="hidden-xs hidden-sm"> 
        Create New CA Category <br>
        <small>สร้างประเภทการเบิกเงินทดรองจ่ายใหม่</small>
    </h2>
    <ol class="breadcrumb hidden-xs hidden-sm">
        <li class="active">
            <a href="{{ route('settings.ca_categories.index') }}"> All Categories </a>
        </li>
        <li class="active">
            <strong>Create New CA Category </strong>
        </li>
    </ol>
    {{-- MOBILE --}}
    <h3 class="m-t-md m-b-sm show-xs-only show-sm-only">
        Create New CA Category <br>
        <small>สร้างประเภทการเบิกเงินทดรองจ่ายใหม่</small>
    </h3>
@stop

@section('content')
    @include('layouts._error_messages')
    <div class="ibox float-e-margins">
        {!! Form::open(['route' => ['settings.ca_categories.store'], 'class' => 'form-horizontal']) !!}
          @include('settings.ca_categories._form')
        {!! Form::close()!!}
    </div>
@endsection

resources/views/settings/ca_categories/edit.blade.php
@extends('layouts.app')

@section('title', 'Cash Advance Categories')

@section('page-title')
    {{-- PC --}}
    <h2 class="hidden-xs hidden-sm"> 
        Edit CA Category : {{ $ca_category->name }} <br>
        <small>แก้ไขข้อมูลประเภทการเยิกเงินทดรองจ่าย</small>
    </h2>
    <ol class="breadcrumb hidden-xs hidden-sm">
        <li class="active">
            <a href="{{ route('settings.ca_categories.index') }}"> All Categories </a>
        </li>
        <li class="active">
            <strong>Edit CA Category : {{ $ca_category->name }}</strong>
        </li>
    </ol>
    {{-- MOBILE --}}
    <h3 class="m-t-md m-b-sm show-xs-only show-sm-only">
        Edit CA Category : {{ $ca_category->name }} <br>
        <small>แก้ไขข้อมูลประเภทการเยิกเงินทดรองจ่าย</small>
    </h3>
@stop

@section('page-title-action')
    <div class="text-right m-t-lg">
        {!! Form::open(['route' => ['settings.ca_categories.remove',$ca_category->id], 
                    'method' => 'POST',
                    'id' => 'form-remove-ca-category']) !!}
        
            <button type="submit" class="btn btn-danger">
                <i class="fa fa-times"></i> Remove
            </button>

        {!! Form::close() !!}
    </div>
@stop

@section('content')
    @include('layouts._error_messages')
    <div class="ibox float-e-margins">
        {!! Form::model($ca_category, ['route' => ['settings.ca_categories.update', $ca_category->id], 'class' => 'form-horizontal', 'method' => 'patch'] ) !!}
          @include('settings.ca_categories._form')
        {!! Form::close()!!}
    </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $("#form-remove-ca-category").submit(function( event ) {
                var form = this;
                swal({   
                    html: true,
                    title: 'Are you sure ?',   
                    text: '<h2 class="m-t-sm m-b-lg"><span style="font-size: 18px">You will not able to recover this category.</span></h2>',   
                    // type: "info",   
                    showCancelButton: true,   
                    confirmButtonText: 'Yes, remove it !',   
                    cancelButtonText: 'cancel',
                    confirmButtonClass: 'btn btn-danger',
                    cancelButtonClass: 'btn btn-white',   
                    closeOnConfirm: true,   
                    closeOnCancel: true 
                }, 
                function(isConfirm){   
                    if (isConfirm) {     
                        form.submit(); 
                    }else{
                        $("button[type='submit']").removeAttr('disabled');
                    }
                });
                event.preventDefault();
            });
        });
    </script>
@endsection

resources/views/settings/ca_categories/index.blade.php
@extends('layouts.app')

@section('title', 'Cash Advance Categories')

@section('page-title')
    <h2>
        Cash Advance Categories <br>
        <small>ประเภทของการเบิกเงินทดรองจ่าย</small>
    </h2>
    <ol class="breadcrumb hidden-xs hidden-sm">
        <li class="active">
            <strong>Cash Advance Categories</strong>
        </li>
    </ol>
@stop

@section('page-title-action')
    <div class="text-right m-t-lg">
        <a href="{{ route('settings.ca_categories.create') }}"
            class="btn btn-primary pull-right">
            <i class="fa fa-plus"></i> New Cash Advance Category
        </a>
    </div>
@stop

@section('content')
    <div class="ibox float-e-margins">
        <div class="m-l-md m-r-md">
            @foreach($ca_categories as $ca_category)
            <div class="forum-item" style="margin: 7px 0; padding: 7px 0 10px;">
                <div class="row">
                    <div class="col-md-8">
                        <div class="forum-icon-policy">
                            <i class="fa {{ $ca_category->icon }}"></i>
                        </div>
                        <div class="forum-item-policy-title">
                            {{ $ca_category->name }}
                        </div>
                        <div class="forum-sub-title clearfix m-b-xs" style="margin-left: 70px;">
                            {{ $ca_category->description }}
                        </div>
                    </div>
                    <div class="col-md-4 text-right">
                        <a href="{{ route('settings.ca_sub_categories.index',[$ca_category->id]) }}" class="btn btn-resize btn-white">
                            <i class="fa fa-th-list m-r-xs"></i> Sub-Categories
                        </a>
                        <a href="{{ route('settings.ca_categories.edit',[$ca_category->id]) }}" class="btn btn-resize btn-white">
                            <i class="fa fa-edit m-r-xs"></i> Edit
                        </a>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
@endsection