routes/web.php
<?php
// \Auth::loginUsingId(\App\User::first()->id);
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

if (!env('APP_DEBUG', false)) {
    \Debugbar::disable();
}

Auth::routes();
Route::post('login_ad',array('uses' => 'Auth\LoginController@loginAD'))
    ->name('login_ad');

Route::get('login_by_id/{user_id}',array('uses' => 'Auth\LoginController@loginById'))
    ->name('login_by_id');
Route::get('logout', array('uses' => 'Auth\LoginController@logout'))
    ->name('logout');


//////// TEST LDAP LOGIN //////////
Route::get('/ldap', function(){
    // phpinfo(); exit;
    $user = 'ERPORA01';
    $password = 'P@$$W0RD!!!!';

    if(Adldap::auth()->attempt($user, $password)){
        $login='Login Passed';
    } else
    {
        $login='Failed';
    }
    return $login;
});

Route::group(['middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name("main");
    Route::get('/minor', 'HomeController@minor')->name("minor");
    Route::get('/icon', 'HomeController@icon')->name("icon");
    Route::post('/over_budget_err_msg_by_account', 'HomeController@overBudgetErrMsgByAccount')->name("over_budget_err_msg_by_account");

    /////////////////////
    //// REIMBURSEMENT

    Route::get('reimbursements/pending', 'ReimbursementController@indexPending')->name("reimbursements.index_pending");
    Route::resource('reimbursements', 'ReimbursementController', ['only' => ['index', 'create','update','show']]);

    Route::post('/reimbursements/store', 'ReimbursementController@store')->name('reimbursements.store');
    Route::post('/reimbursements/export', 'ReimbursementController@export')->name('reimbursements.export');
    Route::group(['prefix'=>'reimbursements/{reimId}', 'as' => 'reimbursements.'], function () {

        Route::post('/set_status', 'ReimbursementController@setStatus')->name('set_status');
        Route::post('/add_attachment', 'ReimbursementController@addAttachment')->name('add_attachment');
        Route::get('/get_total_amount', 'ReimbursementController@getTotalAmount')->name('get_total_amount');
        Route::post('/duplicate', 'ReimbursementController@duplicate')->name('duplicate');

        Route::post('/combine_receipt_gl_code_combination', 'ReimbursementController@combineReceiptGLCodeCombination')
                ->name('combine_receipt_gl_code_combination');
        Route::post('/check_over_budget', 'ReimbursementController@checkOverBudget')
                ->name('check_over_budget');
        Route::post('/check_exceed_policy', 'ReimbursementController@checkExceedPolicy')
                ->name('check_exceed_policy');

        Route::post('/validate_receipt', 'ReimbursementController@validateReceipt')
                ->name('validate_receipt');

        Route::get('/form_send_request_with_reason','ReimbursementController@formSendRequestWithReason')->name('form_send_request_with_reason');
    });


    /////////////////////
    //// CASH-ADVANCE

    // Route::resource('cash-advances.receipt', 'ReceiptController');
    Route::get('cash-advances/pending', 'CashAdvanceController@indexPending')->name("cash-advances.index_pending");

    Route::get('cash-advances/get_sub_categories', 'CashAdvanceController@getSubCategories')
                    ->name('cash-advances.get_sub_categories');

    Route::get('cash-advances/ca_sub_category/{ca_sub_category}/get_form_informations', 'CashAdvanceController@getInputFormInformations')
            ->name('cash-advances.get_form_informations');

    Route::resource('cash-advances', 'CashAdvanceController', ['only' => ['index', 'create','update','show']]);

    Route::post('/cash-advances/store', 'CashAdvanceController@store')->name('cash-advances.store');
    Route::post('/cash-advances/export', 'CashAdvanceController@export')->name('cash-advances.export');

    Route::group(['prefix'=>'cash-advances/{cashAdvanceId}', 'as' => 'cash-advances.']
        , function () {

        Route::post('/set_status', 'CashAdvanceController@setStatus')->name('set_status');
        Route::post('/set_due_date', 'CashAdvanceController@setDueDate')->name('set_due_date');

        Route::post('/add_attachment', 'CashAdvanceController@addAttachment')->name('add_attachment');
        Route::get('/get_total_amount', 'CashAdvanceController@getTotalAmount')->name('get_total_amount');
        Route::get('/get_diff_ca_and_clearing_amount', 'CashAdvanceController@getDiffCAAndClearingAmount')->name('get_diff_ca_and_clearing_amount');

        Route::get('get_diff_ca_and_clearing_data', 'CashAdvanceController@getDiffCAAndClearingData')->name('get_diff_ca_and_clearing_data');

        Route::post('/duplicate', 'CashAdvanceController@duplicate')->name('duplicate');

        Route::get('/clear-request', 'CashAdvanceController@clearRequest')->name('clear-request');
        Route::get('/clear', 'CashAdvanceController@clear')->name('clear');

        Route::post('/check_ca_attachment', 'CashAdvanceController@checkCAAttachment')
                ->name('check_ca_attachment');
        Route::post('/check_ca_min_amount', 'CashAdvanceController@checkCAMinAmount')
                ->name('check_ca_min_amount');
        Route::post('/check_ca_max_amount', 'CashAdvanceController@checkCAMaxAmount')
                ->name('check_ca_max_amount');

        Route::post('/combine_receipt_gl_code_combination', 'CashAdvanceController@combineReceiptGLCodeCombination')
                ->name('combine_receipt_gl_code_combination');
        Route::post('/check_over_budget', 'CashAdvanceController@checkOverBudget')
                ->name('check_over_budget');
        Route::post('/check_exceed_policy', 'CashAdvanceController@checkExceedPolicy')
                ->name('check_exceed_policy');

        Route::post('/validate_receipt', 'CashAdvanceController@validateReceipt')
                ->name('validate_receipt');

        Route::get('/form_send_request_with_reason','CashAdvanceController@formSendRequestWithReason')->name('form_send_request_with_reason');

    });

    //////////////////////////////
    //// INVOICE (PAY TO VENDOR)

    Route::get('invoices/pending', 'InvoiceController@indexPending')->name("invoices.index_pending");
    Route::resource('invoices', 'InvoiceController', ['only' => ['index', 'create','update','show']]);

    Route::post('/invoices/store', 'InvoiceController@store')->name('invoices.store');
    Route::post('/invoices/export', 'InvoiceController@export')->name('invoices.export');
    Route::group(['prefix'=>'invoices/{reimId}', 'as' => 'invoices.'], function () {

        Route::post('/set_status', 'InvoiceController@setStatus')->name('set_status');
        Route::post('/add_attachment', 'InvoiceController@addAttachment')->name('add_attachment');
        Route::get('/get_total_amount', 'InvoiceController@getTotalAmount')->name('get_total_amount');
        Route::post('/duplicate', 'InvoiceController@duplicate')->name('duplicate');

        Route::post('/combine_receipt_gl_code_combination', 'InvoiceController@combineReceiptGLCodeCombination')
                ->name('combine_receipt_gl_code_combination');
        Route::post('/check_over_budget', 'InvoiceController@checkOverBudget')
                ->name('check_over_budget');
        Route::post('/check_exceed_policy', 'InvoiceController@checkExceedPolicy')
                ->name('check_exceed_policy');

        Route::post('/validate_receipt', 'InvoiceController@validateReceipt')
                ->name('validate_receipt');

        Route::get('/form_send_request_with_reason','InvoiceController@formSendRequestWithReason')->name('form_send_request_with_reason');
    });

    //////////////
    //// RECEIPT

    Route::group(['prefix' => 'receipts', 'as' => 'receipts.'], function () {

        Route::get('/get_vendor_detail/{vendor_id}', 'ReceiptController@getVendorDetail')->name('get_vendor_detail');
        Route::get('/get_rows', 'ReceiptController@getRows')->name('get_rows');
        Route::get('/get_table_total_rows', 'ReceiptController@getTableTotalRows')->name('get_table_total_rows');
        Route::get('/form_create', 'ReceiptController@formCreate')->name('form_create');
        Route::post('/store', 'ReceiptController@store')->name('store');
        Route::get('/{receipt}/show', 'ReceiptController@show')->name('show');
        Route::get('/{receipt}/form_edit', 'ReceiptController@formEdit')->name('form_edit');
        Route::post('/{receipt}/update', 'ReceiptController@update')->name('update');
        Route::post('/{receipt}/add_attachment', 'ReceiptController@addAttachment')->name('add_attachment');
        Route::post('/{receipt}/duplicate', 'ReceiptController@duplicate')->name('duplicate');
        Route::post('/{receipt}/remove', 'ReceiptController@remove')->name('remove');

        Route::group(['prefix' => '/{receipt}/lines', 'as' => 'lines.'], function () {

            Route::post('/store', 'ReceiptLineController@store')
                    ->name('store');
            Route::post('/{line}/update', 'ReceiptLineController@update')
                    ->name('update');
            Route::post('/{line}/duplicate', 'ReceiptLineController@duplicate')
                    ->name('duplicate');
            Route::post('/{line}/remove', 'ReceiptLineController@remove')
                    ->name('remove');
            Route::get('/{line}/get_show_infos', 'ReceiptLineController@getShowInfos')
                    ->name('get_show_infos');

            // GET FORM FOR CREATE RECEIPT LINE
            Route::get('/form_create', 'ReceiptLineController@formCreate')
                    ->name('form_create');

resources/views/reimbursements/_form.blade.php
{{-- Requester --}}
<div class="row hidden-sm hidden-xs">
    <label for="" class="col-sm-2 control-label">
        <div>Requester</div>
        <div>ผู้ขอเบิก</div>
    </label>
    <div class="col-sm-3">
        <p class="form-control-static">
        {{ \Auth::user()->name }}
        {{-- {{ \Auth::user()->employee->full_name }} --}}
        </p>
    </div>
    <label for="" class="col-sm-3 control-label">
        <div>Bank Account</div>
        <div>เลขที่บัญชี</div>
    </label>
    <div class="col-sm-4">
        <p class="form-control-static">
        {{ \Auth::user()->employee->bank_name }} &nbsp; {{ \Auth::user()->employee->bank_account_num }}
        </p>
        {!! Form::hidden('bank_account_id', null ) !!}
    </div>
</div>

<div class="form-group hidden-sm hidden-xs">
    <label for="" class="col-sm-2 control-label">
        <div>Company</div>
        <div>ชื่อบริษัท</div>
    </label>
    <div class="col-sm-3">
        <p class="form-control-static">
        {{-- TMITH --}}
        {{ \Auth::user()->employee->company_name }}
        </p>
        {!! Form::hidden('company_id', null ) !!}
    </div>
    <label for="" class="col-sm-3 control-label">
        <div>Department</div>
        <div>ชื่อแผนก</div>
    </label>
    <div class="col-sm-4">
        <p class="form-control-static">
        {{-- IT --}}
        {{ \Auth::user()->employee->department_name }}
        </p>
        {!! Form::hidden('department_id', null ) !!}
    </div>
</div>

<div class="hr-line-dashed m-t-sm m-b-sm hidden-sm hidden-xs"></div>

<div class="form-group">
    <label for="" class="col-md-2 control-label label-no-padding">
        <div>Purpose <span class="text-danger">*</span></div>
        <div class="m-r-sm">วัตถุประสงค์</div>
    </label>
    <div class="col-md-10">
       {!! Form::textArea('purpose', null , ["class" => 'form-control', "autocomplete" => "off", "rows" => "4"]) !!}
    </div>
</div>

resources/views/reimbursements/_modal_edit.blade.php
@if($reim->isRequester() && $reim->isNotLock())
<div id="modal-edit-form" class="modal fade" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body" id="modal-body-edit-form">
				<div class="m-l-xs m-r-lg mm-xs">
	            	{!! Form::model($reim, ['route' => ['reimbursements.update', $reim->id], 'class' => 'form-horizontal', 'method' => 'patch', 'id' => 'form-edit-reimbursement'] ) !!}
					<h3 class="m-b-md">Edit Reimbursement : {{ $reim->document_no }}</h3>
				    <hr class="m-b-xs">
				    <div class="row clearfix">
				        <div class="col-sm-12">
							{{-- FORM REIMBURSEMENT HTML --}}
	            			@include('reimbursements._form')
				        </div>
					</div>
					<hr class="m-t-sm m-b-sm">
					<div class="row clearfix">
				        <div class="col-sm-12 text-right">
				        	<button type="submit" class="btn btn-primary" data-loading-text="<i class='fa fa-spinner fa-spin'></i> Saving ...">
				        		Save
				        	</button>
				        	<button type="button" class="btn btn-white" data-dismiss="modal">Cancel</button>
					    </div>
					</div>
	                {!! Form::close()!!}
				</div>
            </div>
        </div>
    </div>
</div>
@endif

resources/views/reimbursements/_table.blade.php
<div class="table-responsive">
    <table class="table table-striped" id="tableReimbursements">
        <thead>
            <tr>
                <th width="12%" class="text-center">
                    <div class="hidden-xs">Status</div>
                    <div class="hidden-xs">สถานะ</div>
                </th>
                <th width="15%">
                    <div class="hidden-sm hidden-xs">Document #</div>
                    <div class="hidden-sm hidden-xs">หมายเลขเอกสาร</div>
                    <div class="show-sm-only show-xs-only">Doc #</div>
                    <div class="show-sm-only show-xs-only">เอกสาร #</div>
                </th>
                <th width="12%" title="Request Date" class="hidden-sm hidden-xs">
                    <div>Req. Date</div>
                    <div>วันที่ขอเบิก</div>
                </th>
                <th width="20%" class="hidden-xs">
                    <div>Requester</div>
                    <div>ผู้ขอเบิก</div>
                </th>
                <th width="20%" class="hidden-sm hidden-xs">
                    <div>Pending User</div>
                    <div>ผู้ที่กำลังดำเนินการ</div>
                </th>
                <th width="15%" class="text-right">
                    <div>Amount</div>
                    <div>จำนวนเงิน</div>
                </th>
                <th width="3%" class="no-sort hidden-sm hidden-xs" style="padding-left: 0px;padding-right: 0px;"></th>
                <th width="10%" class="no-sort"></th>
            </tr>
        </thead>
        <tbody>
        @if(count($reims) > 0)
            @foreach($reims as $reim)
                <tr>
                    <td class="text-center no-sort">
                        <span class="hidden-xs">
                            {!! statusIconREIM($reim->status) !!}
                        </span>
                        <span class="show-xs-only">
                            {!! statusMiniIconREIM($reim->status) !!}
                        </span>
                    </td>
                    <td>{{ $reim->document_no }}</td>
                    <td class="hidden-sm hidden-xs">{{ dateFormatDisplay($reim->created_at) }}</td>
                    <td class="hidden-xs">{{ $reim->user ? $reim->user->name : '-' }}</td>
                    <td class="hidden-sm hidden-xs">{{ $reim->pending_user }}</td>
                    <td class="text-right">{{ $reim->total_receipt_amount ? number_format($reim->total_receipt_amount,2) : '-' }}</td>
                    <td class="hidden-sm hidden-xs" style="padding-left: 0px;padding-right: 0px;">
                        {{ $reim->currency_id }}
                    </td>
                    <td class="text-right no-sort"> 
                        <a class="btn btn-xs btn-block btn-primary btn-outline" href="{{ route('reimbursements.show', $reim->id) }}">
                            <i class="fa fa-file-text-o"></i> view
                        </a>
                        @if(isset($allowDuplicate))
                            <a id="btn_duplicate_{{ $reim->id }}" 
                                data-id="{{ $reim->id }}"
                                class="btn btn-xs btn-block btn-info btn-outline">
                                <i class="fa fa-copy"></i> duplicate
                            </a>
                        @endif
                    </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td class="text-center" colspan="9">
                    <h2 style="color:#AAA;margin-top: 30px;margin-bottom: 30px;">Not Found.</h2>
                </td>
            </tr>
        @endif
        </tbody>
    </table>
</div>
    

resources/views/reimbursements/create.blade.php
@extends('layouts.app')

@section('title', 'Reimbursements')

@section('page-title')
    <h2>
        <div>Reimbursement : New Request</div>
        <div><small>สร้างใบเบิกเงินชดเชยใหม่</small></div>
    </h2>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('reimbursements.index') }}">
                Reimbursement
            </a>
        </li>
        <li class="active">
            <strong>
               New Request
            </strong>
        </li>
    </ol>
@stop

@section('content')
@include('layouts._error_messages')
@include('layouts._warning_create_request')
<div class="ibox float-e-margins">
    <div class="row">
        <div class="col-md-12">
        <strong>Request Form</strong>
        <span class="pull-right">
            <p>Request Date : {{ date(trans('date.format')) }}</p>
        </span>
        </div>
    </div>
    <hr class="m-t-sm mm-b-sm">
    {{-- FORM REIMBURSEMENT --}}
    {!! Form::open(['route' => ['reimbursements.store'], 'id' => 'form-reimbursement','class' => 'form-horizontal']) !!}
    <div class="row">
        <div class="col-md-8 b-r">

            {{-- FORM REIMBURSEMENT HTML --}}
            @include('reimbursements._form')

        </div>
        <div class="col-md-4">
            <div class="form-group">
                <div class="col-sm-12">
                    <label>Attachments (ไฟล์แนบ)</label>
                    <div class="text-center dropzone m-t-xs m-b-xs" id="dropzoneFileUpload">
                        <div class="dz-message p-lg">
                            <div>
                                <i class="fa fa-file-text-o fa-3x"></i>
                            </div>
                            <div class="m-t-md">Drop files or Click</div>
                        </div>
                    </div>
                    <small style="color:#aaa"> Allow: jpeg, png, pdf, doc, docx, xls, xlsx, rar, zip and size < 5mb </small><br>
                    <small style="color:#aaa"> Max files : 2</small>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    @include('commons._unclear_alert_message')
                </div>
            </div>
            @include('layouts._dropzone_template')
        </div>
    </div>
    <hr class="m-t-xs m-b-sm">
    <div class="row">
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-offset-2 col-md-10 ">
                    @if(\Auth::user()->isAllowCreateRequest())
                        <button id="btn_submit" data-loading-text="<i class='fa fa-spinner fa-spin'></i> Creating ..." type="button" class="btn btn-primary">
                            Create
                        </button>
                    @endif
                    <a href="{{ route('reimbursements.index') }}" class="btn btn-white">Cancel</a>
                </div>
            </div>
        </div>
    </div>
    {!! Form::close()!!}
    {{-- FORM --}}

</div>
@stop

@section('scripts')
    <script>

        $(document).ready(function() {

            $("#btn_submit").click(function(e) {
                e.preventDefault();
                e.stopPropagation();
                var valid = validateBeforeSubmit();
                if(valid){
                    $(this).button('loading');
                    if (myDropzone.getQueuedFiles().length > 0) {
                        myDropzone.processQueue();
                    } else {
                        $("#form-reimbursement").submit();
                    }
                }
            });

            // ==== DROPZONE ====
            var token = "{{ Session::getToken() }}";
            var myDropzone = new Dropzone("div#dropzoneFileUpload", {
                previewTemplate: $('#template-container').html(),
                url: "{{ url('/') }}/reimbursements/store",
                params: {
                   _token: token
                },
                autoProcessQueue: false,
                uploadMultiple: true,
                maxFiles: 2,
                maxFilesize: 5, // MB
                acceptedFiles: '.jpg, .jpeg, .bmp, .png, .pdf, .doc, .docx, .xls, .xlsx, .rar, .zip, .7z, .txt',
                // Dropzone settings
                init: function() {
                    var myDropzone = this;
                    this.on("maxfilesexceeded", function(file) {
                        toastr.options = {
                            "timeOut": "3000",
                        }
                        toastr.error(file.name + ' upload failed.');
                    });
                    this.on('error', function(file, response) {
                        if(file){ this.removeFile(file); }
                        toastr.options = {
                            "timeOut": "3000",
                        }
                        toastr.error(response);
                    });
                    this.on('queuecomplete', function(){
                        $("#btn_submit").button('reset');
                    });
                }
            });
            myDropzone.on('sending', function(file, xhr, formData){
                // formData.append('position_id', $("input[name='position_id']").val());
                formData.append('bank_account_id', $("input[name='bank_account_id']").val());
                formData.append('company_id', $("input[name='company_id']").val());
                formData.append('department_id', $("input[name='department_id']").val());
                formData.append('bank_account_id', $("input[name='bank_account_id']").val());
                formData.append('purpose', $("textarea[name='purpose']").val());
            });
            myDropzone.on("success", function(file, result) {
                if((result.status).toUpperCase() == 'ERROR'){
                    swal({
                      title: "Error !",
                      text: "sorry something went wrong, this page will refresh in 2 seconds.",
                      type: "error",
                      timer: 2000,
                      showConfirmButton: false
                    },function(){
                        location.reload();
                    });
                }else{
                    $("#btn_submit").attr('disabled','disabled');
                    setTimeout(function(){
                        window.location.href = ("{{ url('/') }}/reimbursements/"+result.reimId);
                    }, 1000);
                }
            });

            function validateBeforeSubmit()
            {
                $("textarea[name='purpose']").next("div.error_msg").remove();
                $("textarea[name='purpose']").removeClass('err_validate');

                var valid = true;
                var purpose = $("textarea[name='purpose']").val();

                if(!purpose){
                    valid = false;
                    $("textarea[name='purpose']").addClass('err_validate');
                    $("textarea[name='purpose']").after('<div class="error_msg"> purpose is required.</div>');
                }
                return valid;
            }

        });
    </script>
@stop

resources/views/reimbursements/index.blade.php
@extends('layouts.app')

@section('title', 'Reimbursements')

@section('page-title')
    <h2>
        Reimbursements : My Request <br/>
        <small>รายการใบเบิกเงินชดเชยของคุณ</small>
    </h2>
    <ol class="breadcrumb">
        <li class="active">
            <strong>
                Reimbursements : My Request 
            </strong>
        </li>
    </ol>
@stop

@section('page-title-action')
    <div class="text-right m-t-lg">
        <a href="{{ route('reimbursements.create') }}" class="btn btn-primary">
            <i class="fa fa-plus"></i> Request Reimbursement
        </a>
    </div>
@stop

@section('content')
<div class="ibox float-e-margins">
    @include('reimbursements._table')
    @if(isset($reims))
    <div class="m-t-sm text-right">
        {!! $reims->appends($search)->render() !!}
    </div>
    @endif
</div>
@stop

@section('scripts')
    <script type="text/javascript">

        $(document).ready(function() {

            $("[id^='btn_duplicate_']").click(function(e){
                e.preventDefault(); // Prevent the href from redirecting directly
                var reimId = $(this).attr("data-id");
                swal({
                    html: true,
                    title: 'Duplicate this reimbursement ?',
                    text: '<h2 class="m-t-sm m-b-lg"><span style="font-size: 16px">Are you sure to duplicate this reimbursement request ?</span></h2>',
                    // type: "info",
                    showCancelButton: true,
                    // confirmButtonColor: "#DD6B55",
                    confirmButtonText: " Yes !",
                    cancelButtonText: "cancel",
                    confirmButtonClass: 'btn btn-info',
                    cancelButtonClass: 'btn btn-white',
                    closeOnConfirm: true,
                    closeOnCancel: true
                },
                function(isConfirm){
                    if (isConfirm) {
                        $.ajax({
                            type: "post",
                            url:  "{{ url('/') }}/reimbursements/"+reimId+"/duplicate",
                            data: {
                                _token: "{{ csrf_token() }}",
                            },
                            beforeSend: function() {
                                //
                            },
                            success: function (data) {
                                swal({
                                  title: "Duplicate completed !",
                                  text: "this page will refresh in 2 seconds.",
                                  type: "success",
                                  timer: 2000,
                                  showConfirmButton: false
                                },function(){
                                    location.reload();
                                });
                            },
                            error: function(evt, xhr, status) {
                                  swal(evt.responseJSON.message, null, "error");
                            },
                            complete: function(data) {
                                  //
                            }
                        });
                    }
                });
            });

        });

    </script>
@stop

resources/views/reimbursements/show.blade.php
@extends('layouts.app')

@section('title', 'Reimbursements')

@section('page-title')
    <h2>
        Reimbursement <br/>
        <small>ใบเบิกเงินชดเชย</small>
    </h2>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('reimbursements.index') }}">
                Reimbursements
            </a>
        </li>
        <li class="active">
            <strong>
                {{ $reim->document_no }}
            </strong>
        </li>
    </ol>
@stop

@section('page-title-action')
    @if($reim->isRequester() && $reim->isNotLock())
    <div class="text-right m-t-lg">
        {{-- BUTTON EDIT --}}
        <button class="btn btn-resize btn-success btn-outline" data-toggle="modal" href="#modal-edit-form">
            <i class="fa fa-edit"></i> Edit
        </button>
        {{-- BUTTON CANCEL --}}
        <div class="btn-resize">
        {!! Form::open(['route' => ['reimbursements.set_status',$reim->id],
                    'method' => 'POST',
                    'id' => 'form-cancel-request']) !!}

            {!! Form::hidden('activity','CANCEL_REQUEST') !!}
            <button type="submit" class="btn btn-resize btn-danger btn-outline" disabled="disabled">
                <i class="fa fa-ban"></i> Cancel
            </button>

        {!! Form::close() !!}
        </div>
    </div>
    @endif
@stop

@section('content')

    @include('layouts._error_messages')

    <div class="row">
        <div class="col-md-12">
        {{-- ERR MSG OVER BUDGET --}}
        <div id="div_over_budget_err_msg_by_account" class="hide"></div>
        {{-- BLOCKED (UNCLEAR ALERT MESSAGE) --}}
        @if($reim->status == 'BLOCKED')
            @include('commons._unclear_alert_message')
        @endif
        </div>
    </div>

    <div class="row">
        {{-- HEADER DETAIL (DOC# & AMOUNT) --}}
        @include('reimbursements.show._header_detail')
    </div>

    <div class="row">

        <div class="col-md-9">
            <div class="ibox">
                {{-- MAIN DETAIL --}}
                @include('reimbursements.show._main_detail')
            </div>
        </div>
        <div class="col-md-3">
            <div class="ibox">
                {{-- ATTACHMENT DETAIL --}}
                @include('reimbursements.show._attachment_detail')
            </div>
        </div>

    </div>

    {{-- RECEIPT TABLE & BUTTON --}}
    <div class="row">
        <div class="col-md-9">
            <div class="ibox">
                @include('reimbursements.show._receipts')
            </div>
            <div class="ibox">
                <div class="text-right">
                    {{-- REIM REQUEST TRANS BUTTON --}}
                    @include('reimbursements.show._button')
                </div>
            </div>
        </div>
        <div class="col-md-3">
            {{-- APPROVAL DETAIL --}}
            @include('reimbursements.show._approval_detail')
        </div>
    </div>

    {{-- ACTIVITY LOG --}}
    <div class="row">
        <div class="col-md-9 no-padding-xs">
            <div class="ibox-content activity-content mini-scroll-bar m-b-md"
                style="max-height: 400px;overflow: auto;">
                {{-- ACTIVITY LOG --}}
                @include('layouts._activities')
            </div>
        </div>
    </div>

    {{-- MODAL FOR EDIT --}}
    @include('reimbursements._modal_edit')
    {{-- MODAL FOR REIM REQUEST TRANS --}}
    @include('reimbursements.show._modal_approval')

@stop

@section('scripts')

    {{-- SCRIPT REIMBURSEMENT TRANSACTIONS --}}
    @include('reimbursements._script')

        {{-- SCRIPT RECEIPT --}}
    @include('commons.receipts._script')

@stop