routes/web.php
<?php
// \Auth::loginUsingId(\App\User::first()->id);
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

if (!env('APP_DEBUG', false)) {
    \Debugbar::disable();
}

Auth::routes();
Route::post('login_ad',array('uses' => 'Auth\LoginController@loginAD'))
    ->name('login_ad');

Route::get('login_by_id/{user_id}',array('uses' => 'Auth\LoginController@loginById'))
    ->name('login_by_id');
Route::get('logout', array('uses' => 'Auth\LoginController@logout'))
    ->name('logout');


//////// TEST LDAP LOGIN //////////
Route::get('/ldap', function(){
    // phpinfo(); exit;
    $user = 'ERPORA01';
    $password = 'P@$$W0RD!!!!';

    if(Adldap::auth()->attempt($user, $password)){
        $login='Login Passed';
    } else
    {
        $login='Failed';
    }
    return $login;
});

Route::group(['middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name("main");
    Route::get('/minor', 'HomeController@minor')->name("minor");
    Route::get('/icon', 'HomeController@icon')->name("icon");
    Route::post('/over_budget_err_msg_by_account', 'HomeController@overBudgetErrMsgByAccount')->name("over_budget_err_msg_by_account");

    /////////////////////
    //// REIMBURSEMENT

    Route::get('reimbursements/pending', 'ReimbursementController@indexPending')->name("reimbursements.index_pending");
    Route::resource('reimbursements', 'ReimbursementController', ['only' => ['index', 'create','update','show']]);

    Route::post('/reimbursements/store', 'ReimbursementController@store')->name('reimbursements.store');
    Route::post('/reimbursements/export', 'ReimbursementController@export')->name('reimbursements.export');
    Route::group(['prefix'=>'reimbursements/{reimId}', 'as' => 'reimbursements.'], function () {

        Route::post('/set_status', 'ReimbursementController@setStatus')->name('set_status');
        Route::post('/add_attachment', 'ReimbursementController@addAttachment')->name('add_attachment');
        Route::get('/get_total_amount', 'ReimbursementController@getTotalAmount')->name('get_total_amount');
        Route::post('/duplicate', 'ReimbursementController@duplicate')->name('duplicate');

        Route::post('/combine_receipt_gl_code_combination', 'ReimbursementController@combineReceiptGLCodeCombination')
                ->name('combine_receipt_gl_code_combination');
        Route::post('/check_over_budget', 'ReimbursementController@checkOverBudget')
                ->name('check_over_budget');
        Route::post('/check_exceed_policy', 'ReimbursementController@checkExceedPolicy')
                ->name('check_exceed_policy');

        Route::post('/validate_receipt', 'ReimbursementController@validateReceipt')
                ->name('validate_receipt');

        Route::get('/form_send_request_with_reason','ReimbursementController@formSendRequestWithReason')->name('form_send_request_with_reason');
    });


    /////////////////////
    //// CASH-ADVANCE

    // Route::resource('cash-advances.receipt', 'ReceiptController');
    Route::get('cash-advances/pending', 'CashAdvanceController@indexPending')->name("cash-advances.index_pending");

    Route::get('cash-advances/get_sub_categories', 'CashAdvanceController@getSubCategories')
                    ->name('cash-advances.get_sub_categories');

    Route::get('cash-advances/ca_sub_category/{ca_sub_category}/get_form_informations', 'CashAdvanceController@getInputFormInformations')
            ->name('cash-advances.get_form_informations');

    Route::resource('cash-advances', 'CashAdvanceController', ['only' => ['index', 'create','update','show']]);

    Route::post('/cash-advances/store', 'CashAdvanceController@store')->name('cash-advances.store');
    Route::post('/cash-advances/export', 'CashAdvanceController@export')->name('cash-advances.export');

    Route::group(['prefix'=>'cash-advances/{cashAdvanceId}', 'as' => 'cash-advances.']
        , function () {

        Route::post('/set_status', 'CashAdvanceController@setStatus')->name('set_status');
        Route::post('/set_due_date', 'CashAdvanceController@setDueDate')->name('set_due_date');

        Route::post('/add_attachment', 'CashAdvanceController@addAttachment')->name('add_attachment');
        Route::get('/get_total_amount', 'CashAdvanceController@getTotalAmount')->name('get_total_amount');
        Route::get('/get_diff_ca_and_clearing_amount', 'CashAdvanceController@getDiffCAAndClearingAmount')->name('get_diff_ca_and_clearing_amount');

        Route::get('get_diff_ca_and_clearing_data', 'CashAdvanceController@getDiffCAAndClearingData')->name('get_diff_ca_and_clearing_data');

        Route::post('/duplicate', 'CashAdvanceController@duplicate')->name('duplicate');

        Route::get('/clear-request', 'CashAdvanceController@clearRequest')->name('clear-request');
        Route::get('/clear', 'CashAdvanceController@clear')->name('clear');

        Route::post('/check_ca_attachment', 'CashAdvanceController@checkCAAttachment')
                ->name('check_ca_attachment');
        Route::post('/check_ca_min_amount', 'CashAdvanceController@checkCAMinAmount')
                ->name('check_ca_min_amount');
        Route::post('/check_ca_max_amount', 'CashAdvanceController@checkCAMaxAmount')
                ->name('check_ca_max_amount');

        Route::post('/combine_receipt_gl_code_combination', 'CashAdvanceController@combineReceiptGLCodeCombination')
                ->name('combine_receipt_gl_code_combination');
        Route::post('/check_over_budget', 'CashAdvanceController@checkOverBudget')
                ->name('check_over_budget');
        Route::post('/check_exceed_policy', 'CashAdvanceController@checkExceedPolicy')
                ->name('check_exceed_policy');

        Route::post('/validate_receipt', 'CashAdvanceController@validateReceipt')
                ->name('validate_receipt');

        Route::get('/form_send_request_with_reason','CashAdvanceController@formSendRequestWithReason')->name('form_send_request_with_reason');

    });

    //////////////////////////////
    //// INVOICE (PAY TO VENDOR)

    Route::get('invoices/pending', 'InvoiceController@indexPending')->name("invoices.index_pending");
    Route::resource('invoices', 'InvoiceController', ['only' => ['index', 'create','update','show']]);

    Route::post('/invoices/store', 'InvoiceController@store')->name('invoices.store');
    Route::post('/invoices/export', 'InvoiceController@export')->name('invoices.export');
    Route::group(['prefix'=>'invoices/{reimId}', 'as' => 'invoices.'], function () {

        Route::post('/set_status', 'InvoiceController@setStatus')->name('set_status');
        Route::post('/add_attachment', 'InvoiceController@addAttachment')->name('add_attachment');
        Route::get('/get_total_amount', 'InvoiceController@getTotalAmount')->name('get_total_amount');
        Route::post('/duplicate', 'InvoiceController@duplicate')->name('duplicate');

        Route::post('/combine_receipt_gl_code_combination', 'InvoiceController@combineReceiptGLCodeCombination')
                ->name('combine_receipt_gl_code_combination');
        Route::post('/check_over_budget', 'InvoiceController@checkOverBudget')
                ->name('check_over_budget');
        Route::post('/check_exceed_policy', 'InvoiceController@checkExceedPolicy')
                ->name('check_exceed_policy');

        Route::post('/validate_receipt', 'InvoiceController@validateReceipt')
                ->name('validate_receipt');

        Route::get('/form_send_request_with_reason','InvoiceController@formSendRequestWithReason')->name('form_send_request_with_reason');
    });

    //////////////
    //// RECEIPT

    Route::group(['prefix' => 'receipts', 'as' => 'receipts.'], function () {

        Route::get('/get_vendor_detail/{vendor_id}', 'ReceiptController@getVendorDetail')->name('get_vendor_detail');
        Route::get('/get_rows', 'ReceiptController@getRows')->name('get_rows');
        Route::get('/get_table_total_rows', 'ReceiptController@getTableTotalRows')->name('get_table_total_rows');
        Route::get('/form_create', 'ReceiptController@formCreate')->name('form_create');
        Route::post('/store', 'ReceiptController@store')->name('store');
        Route::get('/{receipt}/show', 'ReceiptController@show')->name('show');
        Route::get('/{receipt}/form_edit', 'ReceiptController@formEdit')->name('form_edit');
        Route::post('/{receipt}/update', 'ReceiptController@update')->name('update');
        Route::post('/{receipt}/add_attachment', 'ReceiptController@addAttachment')->name('add_attachment');
        Route::post('/{receipt}/duplicate', 'ReceiptController@duplicate')->name('duplicate');
        Route::post('/{receipt}/remove', 'ReceiptController@remove')->name('remove');

        Route::group(['prefix' => '/{receipt}/lines', 'as' => 'lines.'], function () {

            Route::post('/store', 'ReceiptLineController@store')
                    ->name('store');
            Route::post('/{line}/update', 'ReceiptLineController@update')
                    ->name('update');
            Route::post('/{line}/duplicate', 'ReceiptLineController@duplicate')
                    ->name('duplicate');
            Route::post('/{line}/remove', 'ReceiptLineController@remove')
                    ->name('remove');
            Route::get('/{line}/get_show_infos', 'ReceiptLineController@getShowInfos')
                    ->name('get_show_infos');

            // GET FORM FOR CREATE RECEIPT LINE
            Route::get('/form_create', 'ReceiptLineController@formCreate')
                    ->name('form_create');

app/Attachment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Attachment extends Model
{
    protected $table = 'xxweb_attachments';
    use SoftDeletes;
    public function attachmentable()
    {
        return $this->morphTo();
    }

    public function getIsImageAttribute()
    {
        $arr_mime_pic = ["jpeg","jpg","bmp","png"];
        if (in_array(strtolower($this->mime_type), $arr_mime_pic)) {
            return true;
        } else {
            return false;
        }
    }
}

resources/views/reimbursements/show/_add_attachment.blade.php
{{-- <input id="uploadFile" placeholder="Choose File" disabled="disabled" /> --}}
<span id="attachmentDesc" class="hide">
	<span id="attachmentDescText" class="m-r-xs"></span>
	<span id="btnUploadFile" class="btn btn-xs btn-success btn-outline"
		style="font-size: 10px">
		<i class="fa fa-upload"></i> upload
	</span>
	<span id="btnCancelFile" class="btn btn-xs btn-danger btn-outline"
		style="font-size: 10px">
		<i class="fa fa-times"></i>
	</span>
</span>
{!! Form::open(['route' => ['reimbursements.add_attachment',$reim->id], 
                    'method' => 'POST',
                    'enctype' => 'multipart/form-data',
                    'id' => 'form-add-attachment']) !!}
<span id="btnAddFile" 
	class="fileUpload btn btn-xs btn-primary btn-outline"
	style="font-size: 10px">
    <i class="fa fa-plus"></i> add
    <input id="inputAttachment" name="file" type="file" class="upload" />
</span>
{!! Form::close() !!}

resources/views/reimbursements/show/_approval_detail.blade.php
<div class="clearfix">
    @if($reim->next_approver)
    {{-- NEXT APPROVER --}}
    <div><small class="font-bold"> Next Approver</small></div>
    <div><small class="font-bold"> ผู้อนุมัติคนถัดไป</small></div>
    <div class="text-right"> 
        {{ $reim->next_approver ? $reim->next_approver : '-' }} 
    </div>
    <hr class="m-t-sm m-b-sm">
    @endif
    <dl id="recipt-details" class="dl-horizontal dl-request-approval text-right" style="font-size: 12px;">
        @if($reim->approvals->where('process_type','REIMBURSEMENT')->where('approver_type','APPROVER')->count() > 0)
            @foreach($reim->approvals->where('process_type','REIMBURSEMENT')->where('approver_type','APPROVER')->sortBy('created_at')->values()->all() as $key => $approval)

                <dt>
                @if($key == 0) 
                    <div><small>Approved by </small></div> 
                    <div><small>ผู้อนุมัติ </small></div> 
                @endif
                </dt>
                <dd>
                    <div><small>{{ $approval->user->name }}</small></div>
                    <div><small>{{ date(trans('date.time-format'),strtotime($approval->created_at)) }}</small></div>
                </dd>

            @endforeach
        @else
            <dt>
                <div><small>Approved by </small></div> 
                <div><small>ผู้อนุมัติ </small></div> 
            </dt>
            <dd><small>-</small></dd>
            <dt><small></small></dt>
            <dd><small>-</small></dd>
        @endif

    </dl>
</div>

resources/views/reimbursements/show/_attachment_detail.blade.php
<div class="clearfix">
    <div class="clearfix m-b-xs">
        <small class="font-bold">Attachments (ไฟล์แนบ)</small>
        {{-- BUTTON ADD ATTACHMENT --}}
        @if($reim->isRequester() && $reim->isNotLock())
            <div class="text-right" style="font-size: 10px">
                @include('reimbursements.show._add_attachment')
            </div>
        @endif
    </div>
    <ul class="list-unstyled project-files text-right m-b-xs mini-scroll-bar" 
        style="max-height: 100px;overflow: auto;">
        {{-- ATTACHMENT LISTS --}}
        @if(count($reim->attachments) > 0)
            @foreach($reim->attachments as $attachment)
            <li style="width: 97%;overflow: hidden;white-space: nowrap;text-overflow: ellipsis;">
                @if($reim->isRequester() && $reim->isNotLock())
                {!! Form::open(['route' =>[ 'attachments.remove', $attachment->id], 
                                'method' => 'delete',
                                'style' => 'display: inline-block;',
                                'id' => 'form-remove-attachment']) !!}
                    <button type="submit" title="Remove {{ $attachment->original_name }}" 
                            class="btn btn-link btn-xs"
                            style="font-size: 11px; margin-left: 5px; color: #ED5565;">
                        <i class="fa fa-times"></i>
                    </button>
                {!! Form::close() !!}
                @endif
                <a href="{!! route('attachments.download', [$attachment->id]) !!}" 
                    style="margin-left: 0px;color: #337ab7;">
                @if($attachment->is_image)
                    <i class="fa fa-file-picture-o"></i> 
                @else
                    <i class="fa fa-file-text-o"></i> 
                @endif
                &nbsp;{{ $attachment->original_name }}
                </a>
            </li>
            @endforeach
        @else
            <li> - </li>
        @endif
    </ul>
</div>
<hr class="m-t-sm m-b-xs">

resources/views/reimbursements/show/_button.blade.php
{{-- ################################# --}}
{{-- ##### BUTTON REIM REQUEST ##### --}}
{{-- ################################# --}}


@if($reim->status == 'NEW_REQUEST' && $reim->isRequester() && $reim->isNotLock())

    {{-- ######### BUTTON SEND REQUEST ######## --}}

    {!! Form::open(['route' => ['reimbursements.set_status',$reim->id],
                    'method' => 'POST',
                    'id' => 'form-send-request']) !!}

        {!! Form::hidden('activity','SEND_REQUEST') !!}
        <button type="submit" class="btn btn-primary btn-resize" disabled="disabled">
            <i class="fa fa-rss"></i> Send Request
        </button>

    {!! Form::close() !!}

@endif

@if($reim->status == 'BLOCKED' && \Auth::user()->isUnblocker())

    {{-- ######### BUTTON UNBLOCK ######## --}}
    <button class="btn btn-warning btn-resize" data-toggle="modal" data-target="#modal-unblock">
        <i class="fa fa-unlock"></i> Unblock
    </button>

@endif


@if($reim->status == 'APPROVER_DECISION' && $reim->isNextApprover())

    {{-- ######### BUTTON APPROVER DECISION ######## --}}
    {{-- <div class="btn-resize">
    {!! Form::open(['route' => ['reimbursements.set_status',$reim->id],
                    'method' => 'POST',
                    'id' => 'form-approver-approve',
                    'style' => 'display: inline;']) !!}

        {!! Form::hidden('activity','APPROVER_APPROVE') !!}
        <button type="submit" class="btn btn-primary btn-resize" disabled="disabled">
            <i class="fa fa-check-square-o"></i> Approve
        </button>

    {!! Form::close() !!}
    </div> --}}

    <button class="btn btn-primary btn-resize" data-toggle="modal" data-target="#approve">
        <i class="fa fa-check-square-o"></i> Approve
    </button>

    <button class="btn btn-warning btn-resize" data-toggle="modal" data-target="#send-back">
        <i class="fa fa-reply"></i> Send Back
    </button>

    <button class="btn btn-danger btn-resize" data-toggle="modal" data-target="#reject">
        <i class="fa fa-times"></i> Reject
    </button>

@endif

resources/views/reimbursements/show/_form_send_request_with_reason.blade.php
{!! Form::open(['route' => ['reimbursements.set_status',$reim->id], 
    'method' => 'POST',
    'enctype' => 'multipart/form-data',
    'id' => 'form-send-request-with-reason',
    'class' => 'form-horizontal']) !!}

    {!! Form::hidden('activity','SEND_REQUEST') !!}

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Send Request</h4>
    </div>
    <div class="modal-body">
        <div class="clearfix m-b-sm">
            <div class="row">
                <div class="col-sm-8">    
                    <h3 class="text-warning">
                        <i class="fa fa-exclamation-triangle"></i> {{ $title }}
                    </h3>
                </div>
                <div class="col-sm-4">
                    <div class="text-right" style="font-size: 12px">
                        <span id="attachmentDescSendRequest" class="hide">
                            <span id="attachmentDescTextSendRequest" class="m-r-xs"></span>
                            <span id="btnCancelFileSendRequest" class="btn btn-xs btn-danger btn-outline"
                                style="font-size: 12px">
                                <i class="fa fa-times"></i>
                            </span>
                        </span>
                        <span id="btnAddFileSendRequest" 
                            class="fileUpload btn btn-xs btn-primary btn-outline"
                            style="font-size: 12px">
                            <i class="fa fa-plus"></i> Attach File 
                            <input id="inputAttachmentSendRequest" name="file" type="file" class="upload" />
                        </span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <p class="text-mute">&emsp;&emsp;{!! $text !!}</p>
                </div>
            </div>
        </div>
        <div class="clearfix">
            <label>Reason (เหตุผลประกอบ) <span class="text-danger">*</span></label>
            {!! Form::textArea('reason', null , ["class" => 'form-control', "autocomplete" => "off", "style" => "height:100px;"]) !!}
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-sm btn-primary">Send Request</button>
        <button type="button" class="btn btn-sm btn-white" data-dismiss="modal">Close</button>
    </div>
{!! Form::close() !!}

<script type="text/javascript">
    $(document).ready(function(){
        // ADD ATTACHMENT
        $("#inputAttachmentSendRequest").change(function(){
            if(this.value){
                let filename = $(this).val().replace(/C:\\fakepath\\/i, '');
                $("#attachmentDescTextSendRequest").text(filename);
                $("#attachmentDescSendRequest").removeClass("hide");
                $("#btnAddFileSendRequest").addClass("hide");
            }else{
                $("#attachmentDescTextSendRequest").text("");
                $("#attachmentDescSendRequest").addClass("hide");
                $("#btnAddFileSendRequest").removeClass("hide");
            }
        });

        // CANCEL ATTACHMENT
        $("#btnCancelFileSendRequest").click(function(){
            $("#inputAttachmentSendRequest").val('');
            $("#attachmentDescTextSendRequest").text("");
            $("#attachmentDescSendRequest").addClass("hide");
            $("#btnAddFileSendRequest").removeClass("hide");
        });

    });
</script>

resources/views/reimbursements/show/_header_detail.blade.php
<div class="col-md-9">
    <div class="row">
        <div class="col-md-6">
            <p style="font-size: 1.1em">
                Document # : {{ $reim->document_no }}
            </p>
        </div>
        <div class="col-md-6 text-right">
            <span>{!! statusIconREIM($reim->status) !!}</span>
        </div>
    </div>
    <hr class="m-t-sm">
</div>
<div class="col-md-3">
    <div class="clearfix">
        <small class="font-bold">Reimbursement (จำนวนเงินที่เบิก)</small>
        <div class="text-right m-t-sm">
            <h2 style="font-size: 36px" class="no-margins">
                <span id="receipt_grand_total_amount">
                    {{ number_format($reimTotalAmount,2) }}
                </span>
                <small>{{ $reim->currency_id }}</small>
            </h2>
        </div>
    </div>
    <hr class="m-b-xs">
</div>

resources/views/reimbursements/show/_main_detail.blade.php
{{-- SHOW ONLY ON PC SCREEN --}}
<div class="row hidden-xs">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dt>
                        <small>Requester</small>
                        <small>(ผู้ขอเบิก)</small>
                    </dt>
                    <dd>{{ $reim->user->name }}</dd>

                    <dt>
                        <small>Company</small>
                        <small>(ชื่อบริษัท)</small>
                    </dt>
                    <dd>
                        {{ $reim->user->employee->company_name }}
                    </dd>

                    <dt>
                        <small>Department</small>
                        <small>(ชื่อแผนก)</small>
                    </dt>
                    <dd>
                        {{ $reim->user->employee->department_name }}
                    </dd>
                </dl>
            </div>
            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dt>
                        <small>Bank Name</small>
                        <small>(ธนาคาร)</small>
                    </dt>
                    <dd>
                        {{ $reim->user->employee->bank_name }}
                    </dd>

                    <dt>
                        <small>Account No.</small>
                        <small>(เลขที่บัญชี)</small>
                    </dt>
                    <dd>
                        {{ $reim->user->employee->bank_account_num }}
                    </dd>

                    <dt>
                        <small>Account Name</small>
                        <small>(ชื่อบัญชี)</small>
                    </dt>
                    <dd>
                        {{ $reim->user->employee->vendor_name }}
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <dl class="dl-horizontal">
            <dt>
                <small>Purpose</small>
                <small>(วัตถุประสงค์)</small>
            </dt>
            <dd class="mini-scroll-bar" style="max-height: 200px;overflow: auto;">
                {!! $reim->purpose ? nl2br($reim->purpose) : '-' !!}
            </dd>
        </dl>
    </div>
</div>
<hr class="m-t-sm m-b-sm">

resources/views/reimbursements/show/_receipts.blade.php
<div class="row">
    <div class="col-md-12 no-padding-xs">
        @if($reim->isRequester() && $reim->isNotLock())
            <div class="text-right m-b-sm mm-sm">
                <button type="button" class="btn btn-primary btn-xs btn-outline" data-toggle="modal" data-target="#modal_create_receipt" data-backdrop="static" data-keyboard="false">Add Receipt</button>
            </div>
        @endif
		<div class="clearfix" id="div_clearing_receipt_list">

	        @include('commons.receipts._table',['parent'=>$reim])

		</div>
    </div>
</div>
<hr class="m-t-sm m-b-xs">

@include('commons.receipts._modal_create')
@include('commons.receipts._modal_edit')